-- Operating view
CREATE OR REPLACE VIEW SURGERY_TREATMENTS AS
SELECT 
       TREATMENTID, DEPARTMENTID, DOCTORID, 
       TREATMENTDATE, DURATION, PATIENT.NAME,
       DATEOFBIRTH, PATIENT.PHONE, SEXE, ILLNESS,
       AVAILABILITY, MAX_NUMBER_PEOPLE
FROM TREATMENT
INNER JOIN PATIENT USING(PATIENTID)
INNER JOIN ROOM USING(ROOMID)
INNER JOIN DEPARTMENT USING(DEPARTMENTID)
WHERE DEPARTMENT.NAME = 'Surgery';

SELECT * FROM SURGERY_TREATMENTS;


-- Query 1
SELECT * FROM SURGERY_TREATMENTS
WHERE SEXE = 'Man'
AND DATEOFBIRTH > TO_DATE('1900-01-01', 'YYYY-MM-DD');


-- Query 2
SELECT 
   EQUIPMENT_STATUS, EQUIPMENT_NAME, 
   EQUIPMENT_PURCHASE_DATE,
   TREATMENTDATE, DURATION, NAME,
   DATEOFBIRTH, SEXE, ILLNESS
FROM SURGERY_TREATMENTS st
INNER JOIN EQUIPEMENT_TREATMENT et
ON et.treatmentid = st.TREATMENTID
LEFT JOIN EQUIPEMENT e
ON e.EQUIPEMENT_ID = et.equipementid;



-- Departments view
CREATE OR REPLACE VIEW DOCTOR_TREATMENTS_COUNT AS
SELECT 
       DOCTOR.NAME AS DOCTOR,
       DOCTOR.SPECIALTY,
       DOCTOR.PHONE,
       DEPARTMENT.NAME AS DEPARTMENT,
       COUNT(TREATMENTID) AS TREATMENT_COUNT
FROM TREATMENT
INNER JOIN DOCTOR USING(DOCTORID)
INNER JOIN DEPARTMENT USING(DEPARTMENTID)
GROUP BY DOCTORID, DOCTOR.NAME, DOCTOR.SPECIALTY, DOCTOR.PHONE, DEPARTMENT.NAME
ORDER BY COUNT(TREATMENTID) DESC;

SELECT * FROM DOCTOR_TREATMENTS_COUNT;


-- Query 1
SELECT DOCTOR, SPECIALTY, PHONE, TREATMENT_COUNT
FROM DOCTOR_TREATMENTS_COUNT
WHERE DEPARTMENT = 'Emergency';

-- Query 2
SELECT DOCTOR, DEPARTMENT, PHONE, SPECIALTY
FROM DOCTOR_TREATMENTS_COUNT
WHERE TREATMENT_COUNT > 5;

-- Query 3
SELECT DOCTOR, DEPARTMENT, PHONE, TREATMENT_COUNT
FROM DOCTOR_TREATMENTS_COUNT
WHERE SPECIALTY = 'Neurology';
