medication_names = [
    "Cetirizine Hydrochloride",
    "Salicylic Acid",
    "diflorasone diacetate",
    "Zaleplon",
    "Doxepin Hydrochloride",
    "Octinoxate",
    "Octisalate",
    "Phenylephrine hydrochloride",
    "Titanium Dioxide",
    "Aluminum Zirconium Octachlorohydrex Gly",
    "norethindrone acetate/ethinyl estradiol",
    "Hydrochlorothiazide",
    "OCTINOXATE",
    "TITANIUM DIOXIDE",
    "alcohol",
    "misoprostol",
    "Triclosan",
    "TITANIUM DIOXIDE",
    "dalteparin sodium",
    "OCTINOXATE OCTISALATE OXYBENZONE",
    "PENTOSTATIN",
    "Chlordiazepoxide Hydrochloride",
    "Metoclopramide",
    "Aluminum hydroxide",
    "Magnesium hydroxide",
    "Simethicone",
    "zolpidem tartrate",
    "ibuprofen",
    "OCTINOXATE",
    "OCTISALATE",
    "TITANIUM DIOXIDE",
    "OLANZAPINE",
    "Medi-First",
    "Asafoetida",
    "Kalmia latifolia",
    "Causticum",
    "Colchicum autumnale",
    "Ferrum metallicum",
    "Gnaphalium polycephalum",
    "Lithium benzoicum",
    "Mercurius praecipitatus ruber",
    "Rhus toxicodendron",
    "Spiraea ulmaria",
    "West Wheat Grass",
    "triclosan",
    "Ibuprofen",
    "SODIUM FLUORIDE",
    "Miconazole Nitrate",
    "Bupropion Hydrochloride",
    "Treatment Set TS348562",
    "BENZTROPINE MESYLATE",
    "Ranitidine",
    "Helium",
    "Oxygen",
    "Lidocaine Hydrochloride",
    "Saline Laxative",
    "oxycodone",
    "FOLIC ACID",
    "Aesculus hippocastanum",
    "Arnica montana",
    "Bellis perennis",
    "Bryonia",
    "Calcarea carbonica",
    "Calcarea fluorica",
    "Cimicifuga racemosa",
    "Cobaltum metallicum",
    "Gnaphalium polycephalum",
    "Hypericum perforatum",
    "Kali carbonicum",
    "Kali phosphoricum",
    "Magnesia phosphorica",
    "Oxalicum acidum",
    "Phosphorus",
    "Rhus toxicodendron",
    "Ruta graveolens",
    "Sepia",
    "Zincum metallicum",
    "acetaminophen",
    "Niacinamide",
    "Adenosine",
    "carbidopa",
    "levodopa",
    "Alcohol",
    "Atenolol",
    "Hydroquinone",
    "Erythromycin",
    "Furosemide",
    "OCTINOXATE",
    "indomethacin",
    "Homosalate",
    "Meradimate",
    "Octinoxate",
    "Titanium Dioxide",
    "White Petrolatum",
    "BACLOFEN",
    "Amino acids",
    "Apis mellifica",
    "Arnica montana",
    "Fucus vesiculosus",
    "Gambogia",
    "Hepar suis",
    "Phosphoricum acidum Pituitary suis",
    "Salicylic Acid",
    "TITANIUM DIOXIDE",
    "OCTINOXATE",
    "ZINC OXIDE",
    "ALCOHOL",
    "Amoxicillin",
    "erythromycin",
    "desvenlafaxine",
    "lorazepam",
    "Promethazine Hydrochloride",
    "diphenhydramine hydrochloride",
    "Avobenzone",
    "Homosalate",
    "Octisalate",
    "Octocrylene",
    "sodium monofluorophosphate",
    "Bismuth subsalicylate",
    "estradiol",
    "Asparagus",
    "IBUPROFEN",
    "Allergenic Extracts Alum Precipitated",
    "Lactulose",
    "Buspirone Hydrochloride",
    "Oxazepam",
    "Triclosan",
    "PRAVASTATIN SODIUM",
    "clonidine hydrochloride",
    "Diltiazem Hydrochloride",
    "buprenorphine",
    "Titanium Dioxide",
    "Pilocarpine Hydrochloride",
    "Imipenem",
    "Metformin Hydrochloride",
    "Citalopram",
    "LORAZEPAM",
    "PREGABALIN",
    "Lamotrigine",
    "ATORVASTATIN CALCIUM",
    "Simvastatin",
    "Acteaminophen",
    "Dextromethorphan HBr",
    "Guaifenesin",
    "Phenylephrine HCl",
    "VERAPAMIL HYDROCHLORIDE",
    "Amlodipine Besylate",
    "Erythropoietin",
    "Acetaminophen",
    "Doxylamine succinate",
    "Phenylephrine HCl",
    "Octinoxate",
    "Salicylic Acid",
    "Atropa Belladonna",
    "Oxymorphone hydrochloride",
    "CLINDAMYCIN",
    "bacitracin zinc",
    "eomycin sulfate",
    "polymyxin b sulfate",
    "pramoxine hydrochloride",
    "SULFACETAMIDE SODIUM",
    "SULFUR",
    "DEXTROSE MONOHYDRATE",
    "AVOBENZONE",
    "OCTINOXATE",
    "OCTISALATE",
    "OXYBENZONE",
    "ONDANSETRON",
    "Acetaminophen",
    "Chlorpehniramine HCl",
    "Dextromethorphan HBr",
    "Phenylephrine HCl",
    "Clonazepam",
    "Dyclonine Hydrochloride",
    "Tricolsan",
    "Acetaminophen",
    "Dextromethorphan HBr",
    "Doxylamine succinate",
    "Phenylephrine HCl",
    "methazolamide",
    "Elaps corallinus",
    "Crotalus horridus",
    "Bryonia",
    "Calc. fluor.",
    "Carduus mar.",
    "Cholesterinum",
    "Cinchona",
    "Digitalis",
    "Hamamelis",
    "Hydrofluoricum acidum",
    "Lachesis",
    "Lycopodium",
    "Naja",
    "Pulsatilla",
    "Vipera berus",
    "Zinc. met.",
    "Aesculus hipp.",
    "Echinacea",
    "sumatriptan succinate",
    "Naproxen sodium",
    "zolpidem tartrate",
    "Sodium Phosphate",
    "avobenzone",
    "octisalate",
    "octocrylene",
    "oxybenzone",
    "octinoxate",
    "Ibuprofen",
    "Lidocaine Hydrochloride",
    "antihemophilic factor/von",
    "Dermatophagoides farinae",
    "ARNICA MONTANA ROOT",
    "TOXICODENDRON PUBESCENS LEAF",
    "SOLANUM DULCAMARA TOP",
    "COMFREY ROOT",
    "SULFUR",
    "SANGUINARIA CANADENSIS ROOT",
    "SUS SCROFA CARTILAGE",
    "SUS SCROFA EMBRYO",
    "SUS SCROFA UMBILICAL CORD",
    "SUS SCROFA PLACENTA",
    ".ALPHA.-LIPOIC ACID",
    "COENZYME A",
    "NADIDE",
    "Pine White",
    "bacitracin zinc",
    "neomycin sulfate",
    "Isosorbide Dinitrate",
    "Lamotrigine",
    "Acetaminophen",
    "Thuja occidentalis",
    "Ciprofloxacin Hydrochloride",
    "fluvoxamine maleate",
    "Metformin Hydrochloride",
    "GUAIFENESIN",
    "DEXTROMETHORPHAN HYDROBROMIDE",
    "PHENYLEPHRINE HYDROCHLORIDE",
    "Avobenzone",
    "Octinoxate",
    "Octisalate",
    "Octocrylene",
    "PYRITHIONE ZINC",
    "RISPERIDONE",
    "lamotrigine",
    "Levetiracetam",
    "Imipenem",
    "OCTINOXATE",
    "Imipramine Hydrochloride",
    "Deer Hair",
    "Isopropyl Alcohol",
    "ferrous gluconate",
    "folic acid",
    "cyanocobalamin",
    "ascorbic acid",
    "Triclosan",
    "Veratrum Album",
    "Colchicum Autumnale",
    "Conium Maculatum",
    "Ipecacuanha",
    "Nux Vomica",
    "Argentum Nitricum",
    "Pulsatilla Pratensis",
    "TRICLOSAN",
    "verapamil hydrochloride",
    "Nicotine Polacrilex",
    "Divalproex sodium",
    "OCTINOXATE",
    "OCTISALATE",
    "Vinorelbine tartrate",
    "Citalopram",
    "Octinoxate",
    "Potassium Chloride",
    "BENZOYL PEROXIDE",
    "HYDROCORTISONE",
    "Acetaminophen",
    "Cocklebur",
    "ATP (Adenosine Triphosphate Disodium)",
    "Malic Acid",
    "Natrum Oxalaceticum",
    "Riboflavinum",
    "Apiolum",
    "Cinnamic Acid",
    "DHEA ",
    "Streptococcus viridans",
    "Salicylic Acid",
    "acebutolol hydrochloride",
    "olmesartan medoxomil",
    "coagulation factor ix (recombinant)",
    "Benzocaine",
    "Clotrimazole",
    "Alprazolam",
    "losartan potassium",
    "Divalproex sodium",
    "urea",
    "Benzalkonium Chloride",
    "Phenylephrine Hydrochloride",
    "ONDANSETRON HYDROCHLORIDE",
    "GLYCERIN",
    "fluocinolone acetonide",
    "Levetiracetam",
    "Promethazine Hydrochloride",
    "Octinoxate",
    "Bryonia",
    "Carduus marianus",
    "Chelidonium majus",
    "Hepar suis",
    "Taraxacum officinale",
    "Triclosan",
    "Glycerin",
    "Paroxetine Hydrochloride",
    "Topiramate",
    "Titanium Dioxide",
    "risperidone",
    "Argentum Viscum",
    "OCTINOXATE",
    "TITANIUM DIOXIDE",
    "Morphine Sulfate",
    "Titanium Dioxide",
    "Ethyl Alcohol",
    "Gabapentin",
    "Flumazenil",
    "Stavudine",
    "nifedipine",
    "Octinoxate",
    "Avena sativa",
    "Equisetum hyemale",
    "Hypericum perforatum",
    "Ulmus fulva",
    "Glycyrrha glabra",
    "Pueraria lobata",
    "OCTINOXATE",
    "ciprofloxacin",
    "fentanyl transdermal system",
    "Alcohol",
    "ISOLEUCINE",
    "LEUCINE",
    "LYSINE",
    "METHIONINE",
    "PHENYLALANINE",
    "THREONINE",
    "TRYPTOPHAN",
    "VALINE",
    "ALANINE",
    "ARGININE",
    "HISTIDINE",
    "PROLINE",
    "SERINE",
    "GLYCINE",
    "CYSTEINE",
    "PHOSPHORIC ACID",
    "Ondansetron Hydrochloride",
    "Minocycline Hydrochloride",
    "paroxetine hydrochloride",
    "Arnica Montana",
    "Rhus Toxicodendron",
    "Phytolacca",
    "Pulsatilla",
    "Ruta Graveolens",
    "black-eyed pea",
    "Oak Mix",
    "hydrocortisone",
    "Mirtazapine",
    "Oxygen",
    "Cladribine",
    "Fluoxetine Hydrochloride",
    "Aralia quinquefolia",
    "Hydrocotyle asiatica",
    "Polygonum multiflorum",
    "Hypothalamus",
    "Pituitarum posterium",
    "Germanium sesquioxide",
    "Pineal",
    "Carisoprodol",
    "carbamazepine",
    "Octinoxate",
    "PIPERACILLIN",
    "Anastrozole",
    "Chlorpromazine Hydrochloride",
    "Eptifibatide",
    "CLINDAMYCIN PHOSPHATE",
    "DOCUSATE SODIUM",
    "Olanzapine",
    "ZINC OXIDE",
    "Atenolol",
    "Lisinopril",
    "Lidocaine",
    "Diazepam",
    "Calcium carbonate",
    "Avobenzone",
    "Homosalate",
    "Octinoxate",
    "Octocrylene",
    "Avobenzone",
    "Octinoxate",
    "Octisalate",
    "HYDROMORPHONE HYDROCHLORIDE",
    "BENZOYL PEROXIDE",
    "amlodipine besylate",
    "Glimepiride",
    "Canary Feathers",
    "Cat Hair",
    "Cattle Epithelia",
    "Chicken Feathers",
    "Dog Epithelia",
    "Duck Feathers",
    "Gerbil Epithelia",
    "Goat Epithelia",
    "Goose Feathers",
    "Mirtazapine",
    "meloxicam",
    "Benzethonium Chloride",
    "Hamamelis Aesculus",
    "Propranolol Hydrochloride",
    "Arnica Aurum 6 10",
    "ENSULIZOLE",
    "HOMOSALATE",
    "OCTINOXATE",
    "OXYBENZONE",
    "TITANIUM DIOXIDE",
    "Ibuprofen",
    "Magnesium hydroxide",
    "Argentum nitricum",
    "Calcarea carbonica",
    "Calcarea silicata",
    "Calcarea sulphurica",
    "Carbo vegetabilis",
    "Natrum carbonicum",
    "Natrum phosphoricum",
    "Nux vomica",
    "Robinia pseudoacacia",
    "Sulphuricum acidum",
    "populus nigra pollen",
    "Tolnaftate",
    "Dextromethorphan Hydrobromide",
    "Guaifenesin",
    "Triclocarban",
    "Levothyroxine Sodium",
    "Agaricus muscarius",
    "Argentum nitricum",
    "Calcarea carbonica",
    "Carbo vegetabilis",
    "Gelsemium sempervirens",
    "Graphites",
    "Mephitis mephitica",
    "Natrum muriaticum",
    "Onosmodium virginianum",
    "Phosphorus",
    "Physostigma venenosum",
    "Pilocarpus",
    "Diphenhydramine HCl",
    "Galantamine Hydrobromide",
    "Famotidine",
    "alcohol",
    "cromolyn sodium",
    "White Petrolatum",
    "acetaminophen",
    "azithromycin",
    "Benazepril Hydrochloride",
    "Sodium Fluoride",
    "Amlodipine Besylate",
    "Felbamate",
    "Sulfamethoxazole",
    "dextromethorphan HBr",
    "guaifenesin",
    "phenylephrine HCl",
    "VANCOMYCIN HYDROCHLORIDE",
    "Dextromethorphan HBr",
    "Guaifenesin",
    "Ethanol",
    "Carisoprodol",
    "Cetirizine HCl",
    "Fexofenadine HCl",
    "OXYMORPHONE HYDROCHLORIDE",
    "Duloxetine",
    "Sodium Monofluorophosphate Silicon Dioxide",
    "Magnesium Sulfate",
    "Granisetron",
    "Morphine Sulfate",
    "Calcium Phosphate Tribasic Colloidal Silicon Dioxide",
    "ATROPINE SULFATE",
    "Potassium Phosphate",
    "Monobasic",
    "Dibasic",
    "SENNOSIDES",
    "Hydrogen Peroxide",
    "sodium phosphate",
    "Irbesartan",
    "Acetaminophen",
    "Caffeine",
    "ETHYL ALCOHOL",
    "ETOMIDATE",
    "Glipizide",
    "GLYCERIN",
    "ARSENIC TRIOXIDE - IPECAC - STRYCHNOS NUX-VOMICA SEED - VERATRUM ALBUM ROOT -",
    "Ibuprofen",
    "Lycopodium Clavatum",
    "Phytolacca",
    "Abies Canadensis",
    "Ammonium Bromatum",
    "Ammonium Muriaticum",
    "Pulsatilla",
    "acetaminophen",
    "diphenhydramine HCl",
    "phenylephrine HCl",
    "TITANIUM DIOXIDE",
    "ZINC OXIDE",
    "Diphenhydramine Hydrochloride",
    "Calendula officinalis",
    "Bellis Perennis",
    "Ledum Palustre",
    "Arnica Montana",
    "Phosphorus",
    "TITANIUM DIOXIDE",
    "Metoprolol Tartrate",
    "LEVOFLOXACIN",
    "Arnica Aurum Equisetum",
    "Ciprofloxacin Hydrochloride",
    "ALCOHOL",
    "Carbamazepine",
    "Sodium Bicarbonate",
    "White Ash",
    "Carduus Oxalis",
    "DIMETHICONE",
    "Diclofenac Sodium",
    "Nicotine Polacrilex",
    "Dog Hair Canis spp.",
    "benztropine mesylate",
    "Menthol",
    "Acetaldehyde",
    "Coumarinum",
    "Histaminum hydrochloricum",
    "Quercetin",
    "Torula cerevisiae",
    "Adrenocorticotrophin",
    "rizatriptan benzoate",
    "NAPROXEN",
    "Sertraline Hydrochloride",
    "PRAVASTATIN SODIUM",
    "Mirtazapine",
    "Castanea vesca",
    "Juniperus communis",
    "Phytolacca",
    "Quercus",
    "Myosotis arvensis",
    "Natrum sulphuricum",
    "Ceanothus americanus",
    "Helianthus annuus",
    "Natrum muriaticum",
    "Lymph (suis)",
    "Spleen (suis)",
    "Thymus (suis)",
    "Valsartan",
    "Acetaminophen",
    "Diphenhydramine HCl",
    "SENNOSIDES A",
    "Aliskiren Hemifumarate",
    "Loratadine",
    "Black Willow",
    "sertraline hydrochloride",
    "morphine sulfate",
    "Arnica Calendula Essence",
    "Naproxen sodium",
    "Terazosin hydrochloride",
    "Dock Sour Sheep Sorrel",
    "Salicylic acid",
    "POTASSIUM CHLORIDE",
    "CAPTOPRIL",
    "escitalopram",
    "Salicylic Acid",
    "Acetaminophen",
    "Dextromethorphan HBr",
    "Doxylamine succinate",
    "chlorine",
    "Aluminum Zirconium Tetrachlorohydrex Gly",
    "Acetaminophen",
    "Urea",
    "Levothyroxine Sodium",
    "Octinoxate ",
    "vobenzone",
    "Aspirin",
    "DOXERCALCIFEROL",
    "Isopropyl Alcohol",
    "ACETAMINOPHEN",
    "Belladonna",
    "Calcarea carbonica",
    "China officinalis",
    "Glonoinum",
    "Lilium Tigrinum",
    "Platinum metallicum",
    "Pulsatilla",
    "Sanguinaria canadensis",
    "Stannum metallicum",
    "Sulfur",
    "Lamotrigine",
    "Olanzapine",
    "hydrocortisone",
    "Mirtazapine",
    "Levothyroxine sodium",
    "Mezereum Comp.",
    "CHLORPROMAZINE HYDROCHLORIDE",
    "Famotidine",
    "Calcium Carbonate",
    "Magnesium Hydroxide",
    "Fluocinonide",
    "Propranolol Hydrochloride",
    "Methadone Hydrochloride",
    "Sugar Maple",
    "Heal Grief",
    "Cichorium Stibium Special Order",
    "Leucine",
    "Phenylalanine",
    "Lysine",
    "Methionine",
    "Isoleucine",
    "Valine",
    "Histidine",
    "Threonine",
    "Tryptophan",
    "Alanine",
    "Glycine",
    "Arginine",
    "Proline",
    "Serine",
    "Tyrosine",
    "Dextrose",
    "Blackberry",
    "Hydrocortisone",
    "loteprednol etabonate",
    "Fluoxetine Hydrochloride",
    "MENTHOL",
    "Aspirin",
    "Caffeine",
    "Pyrithione Zinc",
    "Coal Tar",
    "Cuprum Aceticum 3",
    "Benzethonium chloride",
    "PRAMOXINE HYDROCHLORIDE",
    "GLYCERIN",
    "PHENYLEPHRINE HYDROCHLORIDE",
    "SODIUM FLUORIDE",
    "Diphenhydramine Hydrochloride",
    "Camphor Menthol Methyl Salicylate",
    "ALLANTOIN",
    "quetiapine fumarate",
    "valacyclovir hydrochloride",
    "Ioxilan Injection",
    "Ranitidine",
    "Salicylic Acid",
    "ticarcillin disodium",
    "helminthosporium solani",
    "temazepam",
    "Tizanidine",
    "Titanium Dioxide",
    "Titanium Dioxide",
    "OCTINOXATE",
    "Zinc Oxide",
    "Hepar Magnesium 4",
    "CALCAREA SULPHURICA",
    "Omeprazole",
    "TRICLOSAN",
    "Famotidine",
    "Ethyl Alcohol",
    "Aluminum Chlorohydrate",
    "CIPROFLOXACIN",
    "Mesquite",
    "antihemophilic factor recombinant",
    "Loratadine",
    "Pecan Pollen",
    "DIPHENHYDRAMINE HYDROCHLORIDE",
    "Calamine",
    "LISINOPRIL",
    "Baclofen",
    "glyburide",
    "Nitroglycerin",
    "Flores Formica",
    "quetiapine fumarate",
    "cow milk",
    "Ethyl Alcohol",
    "dextromethorphan hydrobromide",
    "Benzocaine",
    "levothyroxine sodium",
    "Petrolatum",
    "Guaifenesin",
    "Ranitidine",
    "Nicotine Polacrilex",
    "Morphine Sulfate",
    "Soft Cheat Brome",
    "Clozapine",
    "propionibacterium acnes",
    "Nifedipine",
    "Desvenlafaxine",
    "bupropion hydrochloride",
    "Propranolol Hydrochloride",
    "Diphenhydramine HCl",
    "Sorbitol",
    "Titanium Dioxide",
    "Aluminum Zirconium Tetrachlorohydrex GLY",
    "buprenorphine",
    "Diltiazem hydrochloride",
    "ampicillin sodium",
    "Salicylic Acid",
    "Apis mel.",
    "Berber. vulg.",
    "Bryonia",
    "Cantharis",
    "Cinchona",
    "Equisetum hyemale",
    "Ferrum phosphoricum",
    "Gelsemium",
    "Juniperus com.",
    "Pareira",
    "Phosphorus",
    "Plantago",
    "Pulsatilla",
    "Sabal",
    "Terebinthina",
    "Uva-ursi",
    "Echinacea",
    "Hydrastis",
    "Lappa",
    "Solidago",
    "Sodium Monofluorophosphate",
    "BENZETHONIUM CHLORIDE",
    "levocetirizine dihydrochloride",
    "Baclofen",
    "CLADOSPORIUM SPHAEROSPERMUM",
    "Sweet Vernal Grass",
    "LAMOTRIGINE",
    "Podofilox",
    "Iohexol",
    "Dehydro-epi",
    "Estradiol",
    "Pituitarum posterium",
    "Pregnenolone",
    "Progesterone",
    "Spleen",
    "Testosterone",
    "Cefprozil",
    "levalbuterol inhalation",
    "sodium chloride",
    "Neisseria Meningitidis Group A Capsular Polysaccharide Antigen",
    "Neisseria Meningitidis Group C Capsular Polysaccharide Antigen",
    "Neisseria Meningitidis Group Y Capsular Polysaccharide Antigen",
    "OCTINOXATE",
    "TITANIUM DIOXIDE",
    "DIMETHICONE",
    "ALUMINUM HYDROXIDE",
    "STEARIC ACID",
    "HYDROXYPROLINE",
    "triptorelin pamoate",
    "Belladonna",
    "Bellis perennis",
    "Benzoicum acidum",
    "Benzoicum acidum",
    "Causticum",
    "Equisetum hyemale",
    "Lycopodium clavatum",
    "Phosphorus",
    "Plantago major",
    "Rhus aromatica",
    "Sepia",
    "Antibacterial",
    "dimethicone",
    "CIPROFLOXACIN",
    "desloratadine",
    "Robitussin DM",
    "colesevelam hydrochloride",
    "Amoxicillin",
    "Ibuprofen",
    "AVOBENZONE",
    "HOMOSALATE",
    "OCTISALATE",
    "OCTOCRYLENE",
    "OXYBENZONE",
    "Diclofenac Sodium",
    "Citalopram",
    "hydroxyzine pamoate",
    "HYDROQUINONE",
    "CHLOROXYLENOL",
    "ZINC OXIDE TITANIUM DIOXIDE",
    "Ceftriaxone Sodium",
    "OCTINOXATE",
    "Promethazine Hydrochloride",
    "Titanium Dioxide",
    "OCTINOXATE",
    "dimethicone",
    "Benzalkonium Chloride",
    "Allantoin",
    "Nitrofurantoin (monohydrate/macrocrystals)",
    "Hydrocodone Bitartrate",
    "Irbesartan",
    "Tetracycline Hydrochloride",
    "calcipotriene",
    "Magnesium citrate",
    "Guaifenesin",
    "Acetaminophen",
    "Cetirizine HCl",
    "Insulin human",
    "Aspirin",
    "Hydrocortisone",
    "Magnesia phosphorica",
    "Cuprum metallicum",
    "Colocynthis",
    "Phytolacca",
    "Veratrum album",
    "Causticum",
    "Stannum metallicum",
    "Rhus toxicodendron",
    "OCTINOXATE",
    "TITANIUM DIOXIDE",
    "AVOBENZONE",
    "OCTINOXATE",
    "OCTISALATE",
    "OCTOCRYLENE",
    "Risperidone",
    "Mycobacterium phlei",
    "warfarin sodium",
    "quinapril",
    "Zinc Oxide",
    "Buspirone hydrochloride",
    "benzocaine",
    "White Petrolatum",
]
