medication_descriptions = [
    "Drainage of Right Common Iliac Vein, Perc Approach, Diagn",
    "Replacement of Right Eye with Synth Sub, Perc Approach",
    "Dilate L Ext Carotid, Bifurc, w Drug-elut Intra, Perc",
    "Removal of Synthetic Substitute from Urethra, Via Opening",
    "Removal of Synth Sub from L Clavicle, Perc Endo Approach",
    "Bypass Asc Colon to Trans Colon w Autol Sub, Perc Endo",
    "Release Right Anterior Tibial Artery, Perc Endo Approach",
    "Fusion Lumsac Jt w Intbd Fus Dev, Post Appr P Col, Perc",
    "Repair Left Hepatic Duct, Via Natural or Artificial Opening",
    "Insertion of Radioactive Element into GU Tract, Via Opening",
    "Alteration of L Ext Ear with Synth Sub, Perc Endo Approach",
    "Revise Synth Sub in Prostate/Seminal Ves, Perc Endo",
    "Destruction of Right Fallopian Tube, Open Approach",
    "Bypass L Atrium to R Pulm Vn w Nonaut Sub, Perc Endo",
    "Extirpation of Matter from R Inf Parathyroid, Open Approach",
    "Excision of Multiple Parathyroid Glands, Perc Approach",
    "Excision of Right Pelvic Bone, Percutaneous Approach, Diagn",
    "Supplement Left Radius with Nonaut Sub, Perc Endo Approach",
    "Dilation of Pulmonary Valve, Open Approach",
    "Revision of Neuro Lead in Cranial Nrv, Open Approach",
    "Drainage of Left Thorax Tendon, Percutaneous Approach",
    "Control Bleeding in Left Upper Arm, Open Approach",
    "Revision of Infusion Device in R Wrist Jt, Extern Approach",
    "CT Scan L Pelvic Vein w H Osm Contrast, Unenh, Enhance",
    "Inspection of Sacrococcygeal Joint, External Approach",
    "Resection of Left Superior Parathyroid Gland, Open Approach",
    "Revision of Synth Sub in L Sacroiliac Jt, Perc Approach",
    "Supplement L Basilic Vein with Synth Sub, Perc Endo Approach",
    "Repair Left Heart, Open Approach",
    "MRI of Low Extrem Tendon using Oth Contrast, Unenh, Enhance",
    "Fusion C-thor Jt w Autol Sub, Post Appr A Col, Perc",
    "Excision of Left Femoral Shaft, Percutaneous Approach",
    "Release Left Metacarpophalangeal Joint, Open Approach",
    "Drain of L Trunk Muscle with Drain Dev, Perc Endo Approach",
    "Insertion of Other Device into Upper Jaw, Perc Approach",
    "Removal of Autol Sub from L Shoulder Jt, Perc Endo Approach",
    "Supplement Cervical Nerve with Autol Sub, Perc Endo Approach",
    "Supplement L Axilla Art with Synth Sub, Perc Endo Approach",
    "Repair R Up Arm Subcu/Fascia, Perc Approach",
    "Excision of L Inf Parathyroid, Open Approach, Diagn",
    "Reposition Esophagus, External Approach",
    "Supplement R Int Carotid with Synth Sub, Perc Endo Approach",
    "Dilation of Vagina, Open Approach",
    "Dilate Celiac Art w Drug-elut Intra, Perc Endo",
    "Bypass L Fem Art to Peron Art with Synth Sub, Open Approach",
    "Dilation of R Post Tib Art with 3 Drug-elut, Open Approach",
    "Destruction of Chest Skin, External Approach",
    "Fusion of L Shoulder Jt with Synth Sub, Perc Endo Approach",
    "Removal of Drain Dev from Cisterna Chyli, Perc Endo Approach",
    "Restriction of Stomach, Pylorus with Intralum Dev, Endo",
    "Revision of Drainage Device in Thor Jt, Extern Approach",
    "Division of Right Lower Arm and Wrist Tendon, Open Approach",
    "Reattachment of Pancreatic Duct, Open Approach",
    "Extraction of Peroneal Nerve, Open Approach",
    "Excision of Left Cephalic Vein, Open Approach, Diagnostic",
    "Extraction of Right Cornea, External Approach, Diagnostic",
    "Revision of Autol Sub in L Acetabulum, Open Approach",
    "Repair Left Knee Tendon, Percutaneous Approach",
    "Destruction of R Hand Subcu/Fascia, Perc Approach",
    "Drainage of Left Lobe Liver with Drain Dev, Perc Approach",
    "Dilation of Right Hand Artery, Percutaneous Approach",
    "Excision of Pancreatic Duct, Perc Endo Approach",
    "Drainage of Bi Fallopian Tube with Drain Dev, Via Opening",
    "Replace of Pancreat Duct with Synth Sub, Perc Endo Approach",
    "Replace of R Femur Shaft with Synth Sub, Perc Endo Approach",
    "Replacement of Sup Mesent Art with Autol Sub, Open Approach",
    "Supplement Sacrococcygeal Jt with Autol Sub, Open Approach",
    "Excision of Pancreatic Duct, Open Approach, Diagnostic",
    "Change Other Device in Lower Joint, External Approach",
    "Extirpation of Matter from Bladder Neck, Endo",
    "Insertion of Oth Dev into Retroperitoneum, Open Approach",
    "Removal of Synth Sub from L Low Femur, Perc Approach",
    "Excision of Right Eustachian Tube, Open Approach, Diagnostic",
    "Replacement of Back Skin with Synth Sub, Extern Approach",
    "Release Scalp Subcutaneous Tissue and Fascia, Perc Approach",
    "Supplement Right 1st Toe with Synth Sub, Perc Endo Approach",
    "Insertion of Infusion Device into Low Art, Perc Approach",
    "Dilate R Int Carotid, Bifurc, w 3 Drug-elut, Perc Endo",
    "Repair Pelvis Lymphatic, Percutaneous Endoscopic Approach",
    "Insertion of Int Fix into L Clavicle, Perc Approach",
    "Restrict of L Basilic Vein with Extralum Dev, Open Approach",
    "Exercise Treatment of Musculosk Low Back/LE using Prosthesis",
    "Supplement Trigeminal Nerve with Autol Sub, Perc Approach",
    "Fluoroscopy of Head and Neck",
    "Repair Left Hip Joint, Percutaneous Endoscopic Approach",
    "Replacement of Esophagus with Autol Sub, Open Approach",
    "CT Scan of Bi Renal Vein using Oth Contrast, Unenh, Enhance",
    "Inspection of Right Knee Region, External Approach",
    "Bypass L Axilla Art to L Extracran Art, Open Approach",
    "Removal of Infusion Device from Up Art, Perc Endo Approach",
    "Insertion of Int Fix into R Sphenoid Bone, Open Approach",
    "Occlusion of Left Popliteal Artery, Percutaneous Approach",
    "Creation of Penis in Female Perineum, Open Approach",
    "Drainage of Peritoneum with Drain Dev, Perc Endo Approach",
    "Extirpation of Matter from R Axilla Art, Perc Endo Approach",
    "Supplement Left Foot Vein with Synth Sub, Perc Endo Approach",
    "Revision of Ext Fix in R Tarsal, Extern Approach",
    "Removal of Int Fix from L Sternoclav Jt, Perc Approach",
    "CT Scan of Cereb Vent using H Osm Contrast, Unenh, Enhance",
    "Reposition Right Anterior Tibial Artery, Open Approach",
    "Insertion of Hybrid Ext Fix into R Ulna, Perc Endo Approach",
    "Destruction of Left Upper Arm Muscle, Percutaneous Approach",
    "Replace R Lacrimal Bone w Synth Sub, Perc Endo",
    "Replacement of Right Ureter with Nonaut Sub, Open Approach",
    "Remove Synth Sub from Prostate/Seminal Ves, Perc Endo",
    "Bypass L Int Iliac Art to L Femor A w Nonaut Sub, Open",
    "Repair Right Submaxillary Gland, Percutaneous Approach",
    "Excision of Upper Back, Percutaneous Approach",
    "Occlusion of Ascending Colon with Intralum Dev, Via Opening",
    "Repair Right Hip Bursa and Ligament, Percutaneous Approach",
    "CT Scan of Bi Pulm Vein using L Osm Contrast, Unenh, Enhance",
    "Bypass R Fem Art to Low Ex Vein w Autol Art, Perc Endo",
    "Destruction of Left Inguinal Lymphatic, Perc Endo Approach",
    "Bypass Left Kidney Pelvis to Colon, Open Approach",
    "Fusion of Left Wrist Joint with Synth Sub, Perc Approach",
    "Introduce of Local Anesth into Mouth/Phar, Extern Approach",
    "Dilate of Intracran Art with Drug-elut Intra, Open Approach",
    "Revision of Autologous Tissue Substitute in R Breast, Endo",
    "Release Right Knee Joint, External Approach",
    "Dilation of Jejunum, Percutaneous Approach",
    "Restriction of L Main Bronc with Intralum Dev, Perc Approach",
    "Insertion of Other Device into R Knee, Perc Approach",
    "Reposition Right Toe Phalangeal Joint, Perc Endo Approach",
    "Dilation of L Axilla Art with Drug-elut Intra, Open Approach",
    "Revision of Int Fix in R Femur Shaft, Perc Endo Approach",
    "Reposition L Sphenoid Bone with Int Fix, Perc Endo Approach",
    "Reposition R Humeral Head w Monopln Ext Fix, Perc Endo",
    "Restrict Pancreat Duct w Intralum Dev, Perc Endo",
    "Beam Radiation of Radius/Ulna using Neutron Capture",
    "Occlusion of Lg Intest with Extralum Dev, Perc Endo Approach",
    "Replacement of R Ankle Tendon with Nonaut Sub, Open Approach",
    "Drainage of Left Upper Arm Tendon, Open Approach, Diagnostic",
    "Bypass L Int Jugular Vein to Up Vein w Nonaut Sub, Perc Endo",
    "Head and Facial Bones, Destruction",
    "Bypass L Com Iliac Art to R Femor A w Synth Sub, Open",
    "Revision of Drain Dev in Vagina & Cul-de-sac, Open Approach",
    "Dilate L Int Mamm Art, Bifurc, w Drug-elut Intra, Perc Endo",
    "Occlusion of Asc Colon with Extralum Dev, Perc Endo Approach",
    "Revision of Int Fix in Lum Jt, Perc Approach",
    "Removal of Drainage Device from Lower Jaw, Open Approach",
    "Dilation of Left Upper Lobe Bronchus with Intralum Dev, Endo",
    "Restriction of Asc Colon with Intralum Dev, Open Approach",
    "Bypass Colic Vein to Low Vein with Autol Art, Open Approach",
    "Reposition Right Testis, Open Approach",
    "Removal of Synth Sub from R Up Extrem, Extern Approach",
    "Removal of Drainage Device from Left Eye, External Approach",
    "Excision of Head Muscle, Percutaneous Endoscopic Approach",
    "Extraction of Upper Tooth, All, External Approach",
    "Inspection of Left Foot, Percutaneous Endoscopic Approach",
    "Introduce of Analg/Hypnot/Sedat into GU Tract, Via Opening",
    "Bypass R Axilla Art to R Extracran Art w Autol Art, Open",
    "Destruction of Right Greater Saphenous Vein, Perc Approach",
    "Excision of Para-aortic Body, Percutaneous Approach, Diagn",
    "Revision of Int Fix in L Humeral Shaft, Extern Approach",
    "LDR Brachytherapy of Pituitary Gland using Palladium 103",
    "Removal of Synth Sub from Cranial Cav, Perc Endo Approach",
    "Dilation of Jejunum with Intraluminal Device, Via Opening",
    "Dilation of Hymen, Endo",
    "Release Optic Nerve, Percutaneous Endoscopic Approach",
    "Revision of Extraluminal Device in Low Art, Open Approach",
    "Removal of Extraluminal Device from Bladder, Open Approach",
    "Dilation of L Axilla Art with Drug-elut Intra, Perc Approach",
    "Dilation of L Com Iliac Art with 4 Drug-elut, Open Approach",
    "Excision of Left Carotid Body, Percutaneous Approach",
    "Insertion of Monitor Dev into L Diaphragm, Perc Approach",
    "Inspection of Left Shoulder Region, External Approach",
    "Reposition Accessory Nerve, Open Approach",
    "Drainage of Left Lacrimal Bone with Drain Dev, Open Approach",
    "Drainage of Left Ulnar Artery, Percutaneous Approach, Diagn",
    "Revision of Nonaut Sub in T-lum Jt, Open Approach",
    "Dilation of Right Axillary Artery, Percutaneous Approach",
    "Removal of Ext Fix from R Ulna, Extern Approach",
    "Excision of L Up Extrem Lymph, Perc Endo Approach, Diagn",
    "Detachment at Left 4th Toe, Low, Open Approach",
    "Replacement of R Hand Art with Autol Sub, Perc Endo Approach",
    "Dilation of L Radial Art with 2 Intralum Dev, Open Approach",
    "Drainage of Upper Lip, External Approach",
    "Replacement of L Atrium with Zooplastic, Perc Endo Approach",
    "Excision of Left Hip Joint, Percutaneous Endoscopic Approach",
    "Revision of Extralum Dev in Up Intest Tract, Via Opening",
    "Extirpation of Matter from L Fem Art, Open Approach",
    "Drainage of Azygos Vein, Open Approach, Diagnostic",
    "Reposition Right Lesser Saphenous Vein, Open Approach",
    "Insertion of Intraluminal Device into Jejunum, Open Approach",
    "Drainage of Lung Lingula, Percutaneous Approach, Diagnostic",
    "Bypass R Hepatic Duct to Cyst Duct w Intralum Dev, Open",
    "Drainage of Left Brachial Vein, Percutaneous Approach, Diagn",
    "Bypass R Subclav Art to L Low Arm Art w Synth Sub, Open",
    "Release Left Hand Skin, External Approach",
    "Drain of L Peroneal Art with Drain Dev, Perc Endo Approach",
    "Bypass 3 Cor Art from Thor Art w Autol Vn, Perc Endo",
    "Reposition L Sternoclav Jt with Int Fix, Open Approach",
    "Removal of Drainage Device from Low Back, Perc Endo Approach",
    "Repair Right Lower Arm and Wrist Muscle, Perc Endo Approach",
    "Removal of Autol Sub from Coccyx, Perc Endo Approach",
    "Release Right Shoulder Joint, Open Approach",
    "Drainage of Hyoid Bone, Open Approach",
    "Revision of Spacer in L Metacarpocarp Jt, Perc Approach",
    "Bypass R Radial Art to Low Arm Vein w Autol Art, Open",
    "Drainage of R Occipital Bone with Drain Dev, Perc Approach",
    "Destruction of Right Palatine Bone, Percutaneous Approach",
    "Beam Radiation of Urethra using Electrons",
    "Revision of Nonaut Sub in Cervcal Vertebra, Open Approach",
    "Removal of Infusion Device from Cranial Nerve, Open Approach",
    "Supplement Buccal Mucosa with Autol Sub, Extern Approach",
    "Fluency Assessment",
    "Excision of Left Orbit, Percutaneous Approach",
    "Supplement Left Foot Vein with Synth Sub, Open Approach",
    "Removal of Int Fix from R Toe Phalanx Jt, Perc Endo Approach",
    "Bypass L Com Iliac Art to L Int Ilia w Autol Art, Open",
    "Excision of Right Innominate Vein, Percutaneous Approach",
    "Restriction of L Great Saphenous, Perc Endo Approach",
    "CT Scan of Neck using L Osm Contrast, Unenh, Enhance",
    "Fragmentation in Appendix, Percutaneous Endoscopic Approach",
    "Introduce of Oxazolidinones into Mouth/Phar, Perc Approach",
    "Reposition Pulmonary Trunk, Open Approach",
    "Bypass Lower Esophagus to Cutaneous, Endo",
    "Bypass L Hypogast Vein to Low Vein w Autol Art, Perc Endo",
    "Division of Cervical Nerve, Open Approach",
    "Drainage of Aortic Body, Percutaneous Approach",
    "Repair Lumbar Sympathetic Nerve, Percutaneous Approach",
    "Bypass L Ext Iliac Art to Low Ex Art, Open Approach",
    "Repair Left Temporal Bone, Percutaneous Approach",
    "Occlusion L Verteb Art w Intralum Dev, Perc Endo",
    "Reposition Left Foot Muscle, Perc Endo Approach",
    "Bypass Abd Aorta to B Int Ilia w Autol Vn, Perc Endo",
    "Alteration of Left Upper Leg with Autol Sub, Open Approach",
    "Extirpation of Matter from L Foot Art, Bifurc, Open Approach",
    "Exercise Trmt Circ Body w Mech/Electromech Equip",
    "Reposition Left Radius, Percutaneous Endoscopic Approach",
    "Replace of Abd Subcu/Fascia with Autol Sub, Perc Approach",
    "Excision of R Temporomandib Jt, Perc Endo Approach, Diagn",
    "Dilate R Int Mamm Art, Bifurc, w 2 Drug-elut, Open",
    "Introduce Oth Therap Subst in Periph Nrv, Plexi, Perc",
    "Supplement Hemiazygos Vein with Synth Sub, Perc Approach",
    "Insertion of Stimulator Lead into Bladder, Via Opening",
    "Dilation of Portal Vein with Intralum Dev, Perc Approach",
    "Beam Radiation of Lung using Electrons, Intraoperative",
    "Supplement Left Palatine Bone with Synth Sub, Open Approach",
    "Repair Nasal Bone, External Approach",
    "Remove Drain Dev from Low Intest Tract, Perc Endo",
    "Occlusion of L Fem Art with Intralum Dev, Perc Endo Approach",
    "Excision of Left Wrist Region, Open Approach",
    "Bypass Left Femoral Artery to Low Ex Art, Open Approach",
    "Supplement L Up Arm Muscle with Nonaut Sub, Open Approach",
    "Dilate Sup Mesent Art, Bifurc, w Intralum Dev, Perc Endo",
    "Repair Left Foot Muscle, Percutaneous Approach",
    "Removal of Int Fix from R Shoulder Jt, Perc Approach",
    "Bypass Abd Aorta to Low Ex Art w Nonaut Sub, Perc Endo",
    "Introduction of Nutritional into Subcu, Perc Approach",
    "Restrict Pelvis Lymph w Extralum Dev, Perc Endo",
    "Revision of Infusion Dev in Fem Perineum, Perc Endo Approach",
    "Extirpate matter from Uterine Support Struct, Perc Endo",
    "Removal of Artificial Sphincter from Bladder, Endo",
    "Extirpate matter from L Shoulder Bursa/Lig, Perc Endo",
    "Removal of Autol Sub from L Humeral Head, Open Approach",
    "Bypass L Atrium to Pulm Vn Cnfl with Autol Vn, Open Approach",
    "Destruction of Thor Aorta Desc, Perc Endo Approach",
    "Revision of Int Fix in R Knee Jt, Open Approach",
    "Occlusion of Superior Mesenteric Vein, Open Approach",
    "Reposition Right Tibia with Monopln Ext Fix, Perc Approach",
    "Excision of Left Upper Arm, Percutaneous Endoscopic Approach",
    "Bypass L Subclav Art to Bi Up Arm Art w Autol Art, Open",
    "Supplement L Abd Bursa/Lig w Synth Sub, Perc Endo",
    "Occlusion L Sperm Cord w Intralum Dev, Perc Endo",
    "Reposition Left Metacarpal, Open Approach",
    "Fusion C-thor Jt w Nonaut Sub, Post Appr A Col, Open",
    "Removal of Autol Sub from Great Vessel, Open Approach",
    "Drainage of Right Thorax Tendon, Perc Endo Approach, Diagn",
    "Repair Oculomotor Nerve, Open Approach",
    "Drain R Metacarpocarp Jt w Drain Dev, Perc Endo",
    "Removal of Radioact Elem from Cranial Cav, Open Approach",
    "Bypass R Ext Jugular Vein to Up Vein w Autol Vn, Perc Endo",
    "Drainage of Ileocecal Valve, Percutaneous Approach",
    "Reattachment of Upper Tooth, All, Open Approach",
    "Replace of Chest Subcu/Fascia with Synth Sub, Open Approach",
    "Insertion of Tissue Expander into Right Nipple, Via Opening",
    "Removal of Radioactive Element from Lower Jaw, Perc Approach",
    "Replace R Low Arm Skin w Synth Sub, Full Thick, Extern",
    "Fluoroscopy of L Temporomand Jt using Oth Contrast",
    "Repair Right Lower Arm, Percutaneous Endoscopic Approach",
    "Muscle Perform Treatment of Neuro Head, Neck using Orthosis",
    "Drainage of Left Parotid Gland, Open Approach, Diagnostic",
    "Removal of Autol Sub from Mediastinum, Perc Endo Approach",
    "Restriction of R Neck Lymph with Extralum Dev, Perc Approach",
    "Revision of Monitoring Device in Stomach, Via Opening",
    "Drainage of Pancreas, Perc Endo Approach, Diagn",
    "Reposition L Humeral Head with Hybrid Ext Fix, Open Approach",
    "Dilation of L Peroneal Art with 4 Drug-elut, Perc Approach",
    "Replace R Hip Jt, Acetab w Metal, Uncement, Open",
    "Removal of Drain Dev from R Finger Phalanx Jt, Open Approach",
    "Drainage of Thoracic Duct, Open Approach, Diagnostic",
    "Repair Thalamus, Percutaneous Endoscopic Approach",
    "Supplement R Thorax Bursa/Lig with Autol Sub, Open Approach",
    "Restriction of Cystic Duct, Percutaneous Approach",
    "Drainage of Right Sacroiliac Joint, Open Approach, Diagn",
    "Fragmentation in Common Bile Duct, Open Approach",
    "Destruction of Right Radius, Open Approach",
    "Change Splint on Face",
    "Restrict Cystic Duct w Intralum Dev, Perc Endo",
    "Excision of Nasal Septum, Perc Endo Approach, Diagn",
    "Drainage of Hyoid Bone, Percutaneous Endoscopic Approach",
    "Revision of Synth Sub in Up Muscle, Extern Approach",
    "Fluoroscopy of Right Pulmonary Artery using H Osm Contrast",
    "Repair Right Hand, Percutaneous Approach",
    "Insert of Infusion Dev into R Pulm Art, Perc Endo Approach",
    "Introduction of Oth Therap Subst into Eye, Via Opening",
    "Bypass Descend Colon to Cutan with Synth Sub, Perc Approach",
    "Repair Left Foot, External Approach",
    "Transfer Hypoglossal Nerve to Vagus Nerve, Open Approach",
    "Restriction of L Radial Art with Extralum Dev, Open Approach",
    "Release Sacral Sympathetic Nerve, Percutaneous Approach",
    "Revision of Synth Sub in R Finger Phalanx, Open Approach",
    "Extirpation of Matter from R Sphenoid Sinus, Perc Approach",
    "Revision of Infusion Dev in T-lum Disc, Perc Endo Approach",
    "Revision of Autol Sub in L Breast, Extern Approach",
    "Dressing of Right Upper Leg using Bandage",
    "Dilate R Ext Iliac Art w Drug-elut Intra, Perc Endo",
    "Restriction of Left Axillary Vein, Percutaneous Approach",
    "Introduction of Destr Agent into Fem Reprod, Via Opening",
    "Bypass R Axilla Art to R Low Arm Art w Autol Art, Open",
    "Introduce Local Anesth in Skin/Mucous Mem, Extern",
    "Dilate of R Verteb Art with 3 Drug-elut, Perc Endo Approach",
    "Release Right Toe Phalangeal Joint, Perc Endo Approach",
    "Revision of Synth Sub in L Finger Phalanx Jt, Open Approach",
    "Revision of Nonaut Sub in Hepatobil Duct, Perc Endo Approach",
    "Occlusion of Carina with Extraluminal Device, Perc Approach",
    "Supplement L Ventricle with Zooplastic, Perc Endo Approach",
    "Repair Superior Vena Cava, Percutaneous Approach",
    "Revise of Infusion Dev in R Metatarsotars Jt, Open Approach",
    "Restriction of Esophagus, Open Approach",
    "Excision of Right Middle Lobe Bronchus, Endo, Diagn",
    "Replacement of L Temporal Bone with Autol Sub, Open Approach",
    "Dilation of R Ext Iliac Art with 2 Drug-elut, Perc Approach",
    "Change Other Device in Up Intest Tract, Extern Approach",
    "Removal of Autol Sub from L Eye, Extern Approach",
    "Dilation of R Mid Lobe Bronc with Intralum Dev, Via Opening",
    "Fragmentation in Left Hepatic Duct, Endo",
    "Revision of Drainage Device in Lumsac Disc, Extern Approach",
    "Introduction of Oth Hormone into Central Art, Perc Approach",
    "Planar Nucl Med Imag of Abd & Pelvis using Indium 111",
    "Destruction of Right Fibula, Perc Endo Approach",
    "Dilate L Com Carotid, Bifurc, w 4 Drug-elut, Perc",
    "Insertion of Int Fix into L Metatarsotars Jt, Perc Approach",
    "Restriction of Left Brachial Artery, Percutaneous Approach",
    "Extirpate matter from L Ankle Bursa/Lig, Perc Endo",
    "Repair Right Clavicle, Percutaneous Endoscopic Approach",
    "Occlusion R Ext Jugular Vein w Intralum Dev, Open",
    "Dilate L Peroneal Art, Bifurc, w Drug-elut Intra, Perc Endo",
    "Monitoring of Gastrointestinal Pressure, Endo",
    "Extirpation of Matter from Left Lung, Via Opening",
    "Bypass L Com Iliac Art to B Int Ilia w Autol Art, Perc Endo",
    "Insertion of Intralum Dev into L Renal Vein, Open Approach",
    "Revision of Nonaut Sub in R Glenoid Cav, Extern Approach",
    "Excision of Right Axilla, Percutaneous Approach, Diagnostic",
    "Bypass Bi Ureter to Colon w Nonaut Sub, Perc Endo",
    "Replacement of R Fem Art with Nonaut Sub, Perc Endo Approach",
    "Excision of Cervical Vertebral Joint, Open Approach",
    "Repair Right Upper Leg Tendon, Percutaneous Approach",
    "Excision of Rectum, Via Natural or Artificial Opening",
    "Extirpation of Matter from L Shoulder Tendon, Perc Approach",
    "Plain Radiography of Uterus & Fallopian using H Osm Contrast",
    "Revision of Synthetic Substitute in L Tarsal, Open Approach",
    "Extirpation of Matter from R Sperm Cord, Perc Approach",
    "Revision of Nonaut Sub in Penis, Open Approach",
    "Transfer Left Upper Leg Muscle, Open Approach",
    "Revision of Drainage Device in R Carpal Jt, Extern Approach",
    "Alteration of Left Axilla with Nonaut Sub, Open Approach",
    "Destruction of Esophagogastric Junction, Perc Approach",
    "Transfuse Autol Frozen Red Cells in Central Art, Open",
    "Excision of Buccal Mucosa, Percutaneous Approach",
    "Revision of Bone Stim in Up Bone, Extern Approach",
    "Revision of Int Fix in R Toe Phalanx, Perc Approach",
    "CT Scan of Bi Int Carotid using L Osm Contrast",
    "Excision of Anus, Via Natural or Artificial Opening, Diagn",
    "Removal of Infusion Device from L Hip Jt, Perc Endo Approach",
    "Repair Right Ulna, Percutaneous Endoscopic Approach",
    "Drainage of Spinal Canal, Open Approach",
    "Supplement L Sacroiliac Jt w Nonaut Sub, Perc Endo",
    "Dilate Gastric Art, Bifurc, w Drug-elut Intra, Perc Endo",
    "Restrict R Com Iliac Vein w Intralum Dev, Perc Endo",
    "Hyperthermia of Hard Palate",
    "Bursae and Ligaments, Revision",
    "Supplement R Foot Art with Autol Sub, Perc Endo Approach",
    "Revision of Monitoring Device in Great Vessel, Open Approach",
    "Destruction of Bilateral Lungs, Endo",
    "Replacement of Left Eye with Autol Sub, Perc Approach",
    "Supplement Lesser Omentum with Synth Sub, Open Approach",
    "Removal of Synth Sub from Abd Wall, Extern Approach",
    "Release Left Finger Phalanx, Open Approach",
    "Drainage of Bilateral Fallopian Tubes, Endo",
    "Removal of Radioactive Element from Up Jaw, Extern Approach",
    "Drainage of Pancreatic Duct, Percutaneous Approach, Diagn",
    "LDR Brachytherapy of Pancreas using Palladium 103",
    "MRI of Bi Pelvic Vein using Oth Contrast, Unenh, Enhance",
    "Dilation of 1 Cor Art with Radioact Intralum, Perc Approach",
    "Revision of Other Device in Cranial Cavity, Extern Approach",
    "Dilate of Sup Mesent Art with Drug-elut Intra, Open Approach",
    "Revise of Nonaut Sub in R Metacarpophal Jt, Extern Approach",
    "Dilate L Com Iliac Art w Intralum Dev, Perc Endo",
    "Insert of Endobronch Valve into R Main Bronc, Perc Approach",
    "Release Right Metacarpophalangeal Joint, Open Approach",
    "Removal of Drainage Device from L Elbow Jt, Perc Approach",
    "Excision of Cervical Vertebral Disc, Perc Approach, Diagn",
    "Reposition Right Acetabulum, Perc Endo Approach",
    "Destruction of Thyroid Gland, Perc Endo Approach",
    "HDR Brachytherapy of Chest Wall using Palladium 103",
    "Drainage of Left Ankle Region with Drain Dev, Open Approach",
    "Excision of Left Toe Phalangeal Joint, Percutaneous Approach",
    "Supplement L Verteb Vein with Nonaut Sub, Open Approach",
    "Revision of Ext Fix in R Ulna, Extern Approach",
    "Dilate R Subclav Art, Bifurc, w 2 Drug-elut, Open",
    "Supplement Epiglottis with Synth Sub, Open Approach",
    "Excision of Glomus Jugulare, Percutaneous Approach",
    "Exercise Treatment of Circ Body using Assist Equipment",
    "Revise Tissue Expander in Up Extrem Subcu/Fascia, Open",
    "Replacement of Right Radius with Synth Sub, Perc Approach",
    "Insertion of Reservoir into Abd Subcu/Fascia, Perc Approach",
    "Release Right Upper Leg Tendon, Percutaneous Approach",
    "Removal of Infusion Device from Up Art, Extern Approach",
    "Release Thoracolumbar Vertebral Joint, Perc Endo Approach",
    "Supplement L Ring Finger with Nonaut Sub, Perc Endo Approach",
    "Alteration of Lower Lip with Autol Sub, Extern Approach",
    "Drainage of Genitalia Skin, External Approach, Diagnostic",
    "Repair Sciatic Nerve, Percutaneous Approach",
    "Excision of Left External Iliac Artery, Perc Approach, Diagn",
    "Introduction of Oth Diagn Subst into Nose, Extern Approach",
    "Supplement L Up Leg Subcu/Fascia w Autol Sub, Open",
    "Excision of Neck, External Approach, Diagnostic",
    "Removal of Ext Fix from R Femur Shaft, Extern Approach",
    "Drainage of Right Sphenoid Bone, Perc Endo Approach, Diagn",
    "Aural Rehabilitation Status Assessment using AV Equipment",
    "Resection of Large Intestine, Endo",
    "Destruction of Left External Iliac Artery, Open Approach",
    "Dilate L Brach Art, Bifurc, w 2 Drug-elut, Open",
    "Destruction of Cerebral Ventricle, Percutaneous Approach",
    "Bypass L Great Saphenous to Low Vein w Synth Sub, Open",
    "Dilate of Azygos Vein with Intralum Dev, Perc Endo Approach",
    "Insertion of Other Device into L Wrist, Perc Approach",
    "CT Scan Chest, Abd & Pelvis w Oth Contrast, Unenh, Enhance",
    "Fragmentation in Right Parotid Duct, External Approach",
    "Drain L Tunica Vaginalis w Drain Dev, Perc Endo",
    "Extirpation of Matter from Right Ovary, Open Approach",
    "Supplement R Vas Deferens with Autol Sub, Perc Endo Approach",
    "Transfer Trigeminal Nerve to Vagus Nerve, Open Approach",
    "Insertion of Radioact Elem into Hepatobil Duct, Via Opening",
    "Extirpate matter from Chordae Tendineae, Perc Endo",
    "Reposition L Up Femur with Monopln Ext Fix, Perc Approach",
    "Excision of L Abd Bursa/Lig, Perc Endo Approach",
    "Chiropractic Manipulation of Abdomen, Extra-Articular",
    "Drainage of Right Main Bronchus, Perc Endo Approach",
    "Change Drainage Device in Liver, External Approach",
    "Extirpation of Matter from R Adrenal Gland, Perc Approach",
    "Insertion of Infusion Device into Left Atrium, Open Approach",
    "Drainage of Transverse Colon with Drain Dev, Via Opening",
    "Replace of L Humeral Shaft with Nonaut Sub, Perc Approach",
    "Insertion of Intralum Dev into R Brach Vein, Open Approach",
    "HDR Brachytherapy of Jejunum using Palladium 103",
    "Dilate L Popl Art, Bifurc, w Intralum Dev, Perc",
    "Removal of Nonaut Sub from Mouth/Throat, Endo",
    "Alteration of R Axilla with Nonaut Sub, Perc Endo Approach",
    "Insert VAD Reservoir in R Low Arm Subcu/Fascia, Open",
    "Release Right Patella, Percutaneous Approach",
    "Revision of Other Device in Pericard Cav, Perc Endo Approach",
    "Replacement of L Kidney Pelvis with Synth Sub, Open Approach",
    "Dilate 4+ Cor Art, Bifurc, w 2 Intralum Dev, Perc",
    "Alteration of Left Axilla with Autol Sub, Perc Endo Approach",
    "Transfer Lower Lip, External Approach",
    "Supplement L Temporomandib Jt with Autol Sub, Open Approach",
    "Inspection of Right Ankle Joint, Perc Endo Approach",
    "Revise of Synth Sub in Sacrococcygeal Jt, Perc Endo Approach",
    "Release Left Main Bronchus, Endo",
    "Drainage of Left Vertebral Artery, Percutaneous Approach",
    "Drainage of Right Thyroid Gland Lobe, Perc Endo Approach",
    "Replace of Papillary Muscle with Nonaut Sub, Open Approach",
    "LDR Brachytherapy of Pancreas using Californium 252",
    "Restriction of Right Hand Artery, Open Approach",
    "Reposition Left Neck Muscle, Open Approach",
    "Drainage of Carina, Percutaneous Endoscopic Approach, Diagn",
    "Cochlear Implant Assessment using Hear Aid Equipment",
    "Release Left Diaphragm, Open Approach",
    "Bypass R Int Iliac Art to R Ext Ilia w Synth Sub, Open",
    "Introduce Electrol/Water Bal in Central Vein, Open",
    "Revision of Drainage Device in Up Intest Tract, Via Opening",
    "Reposition Right Tibia with Monopln Ext Fix, Perc Approach",
    "Revision of Nonaut Sub in L Up Femur, Open Approach",
    "Introduce Oth Therap Subst in Male Reprod, Perc",
    "Revision of Monitor Dev in Cranial Nrv, Extern Approach",
    "Bypass R Innom Vein to Up Vein w Nonaut Sub, Perc Endo",
    "Removal of Nonautologous Tissue Substitute from L Eye, Endo",
    "Replacement of L Pelvic Bone with Autol Sub, Open Approach",
    "Repair Left Radial Artery, Percutaneous Endoscopic Approach",
    "Replacement of Up Tooth, All, with Autol Sub, Open Approach",
    "Fusion of Right Finger Phalangeal Joint, Open Approach",
    "Excision of Left Face Vein, Open Approach, Diagnostic",
    "Insertion of Neuro Lead into Brain, Perc Endo Approach",
    "Reposition Left Toe Phalanx, External Approach",
    "Drainage of Right Inguinal Region, Perc Approach, Diagn",
    "Revision of Synthetic Substitute in Low Art, Perc Approach",
    "Bypass R Vas Deferens to R Vas Def w Synth Sub,",
]
