treatment_descriptions = [
    "Brain condition NOS",
    "Gastrostomy comp - mech",
    "Mal neo descend colon",
    "Cardiac arrest",
    "Central hearing loss",
    "Hx of myeloid leukemia",
    "Shyness disorder-child",
    "Sec DM other uncontrld",
    "Chondromalacia patellae",
    "Hx of leukemia NEC",
    "Motor neuron disease NEC",
    "Anomalous av excitation",
    "H simplex otitis externa",
    "Obstruct labor NOS-deliv",
    "T7-t12 fx-op/ant crd syn",
    "Toxoplasmosis site NEC",
    "Hx pathological fracture",
    "TB of kidney-exam unkn",
    "Acute pericarditis NEC",
    "Cl skul vlt fx-deep coma",
    "Loss control mv-pers NOS",
    "War inj:WMD NOS",
    "Splenic sequestration",
    "Mal neo soft tis thorax",
    "Deep 3rd burn trunk NEC",
    "Corneal disorder NEC",
    "Psychogenic gu dis NOS",
    "Primary carnitine defncy",
    "Tox eff lead compnd NOS",
    "3rd brn w loss-head mult",
    "Crushing injury foot",
    "TB sp crd absc-exam unkn",
    "Oth mono leuk w rmsion",
    "Subarachnoid hem-no coma",
    "Continuous leakage",
    "Glaucomatous flecks",
    "Diplegia of upper limbs",
    "Late effect fracture NEC",
    "Trichomonal prostatitis",
    "Malignant neo larynx NEC",
    "1st deg burn head NOS",
    "Underweight",
    "Chronic prostatitis",
    "Cl lumbar fx w cord inj",
    "DMI ophth nt st uncntrld",
    "Irradiation cystitis",
    "Staph pneumonia NEC",
    "Fall-occ unpower aircraf",
    "Burning bedclothes",
    "Hx-hodgkins disease",
    "3rd burn w loss-forearm",
    "Subarach hem-brief coma",
    "Surgical convalescence",
    "Anatomical narrow angle",
    "Edema in preg-delivered",
    "Common truncus",
    "Lordosis in oth dis",
    "Adv eff antithyroid agnt",
    "Ab mammogram NOS",
    "Mv n-traf NEC-anim rider",
    "Psychogenic disorder NEC",
    "Heat effect NOS",
    "NB intraven hem,grade ii",
    "Septicemia in labor-unsp",
    "Mv coll w ped-ped cycl",
    "Pulmon TB NEC-micro dx",
    "Opn cort contus-brf coma",
    "Extravasn vesicant NEC",
    "Talipes equinovarus",
    "Congen limb anomaly NOS",
    "Hemarthrosis-l/leg",
    "Mantle cell lymph multip",
    "Streptobacillary fever",
    "Loose body-forearm",
    "Monteggias fx-open",
    "Cl skul fx NEC-deep coma",
    "Ice hockey",
    "Cl skul base fx-mod coma",
    "Uterine endometriosis",
    "Malignant ascites",
    "Placenta previa-deliver",
    "Fire in bldg-fumes NOS",
    "Mal neo resp system NOS",
    "Fx upper humerus NEC-opn",
    "Dis mitochondrial metab",
    "Comp-oth vasc dev/graft",
    "Malfun neuro device/graf",
    "Spinal cord injury NOS",
    "Brain neoplasm NOS",
    "Ob pyemic embol-postpart",
    "Referral-no exam/treat",
    "Dysplasia of cervix NOS",
    "Malig neuroendo ca NOS",
    "Cicatricial lagophthalm",
    "Sparganosis",
    "Cns disorder NOS",
    "70-79% bdy brn/60-69% 3d",
    "T7-t12 fx-op/com crd les",
    "TB epididymis-micro dx",
    "Blood vessel injury NOS",
    "Sprain rotator cuff",
    "Injury oculomotor nerve",
    "Genetic anomaly leukocyt",
    "Hereditary spherocytosis",
    "Psychogen musculskel dis",
    "Acq hemolytic anemia NOS",
    "Malposition NEC-antepart",
    "Pap smear cervix w HGSIL",
    "Preg w incon fetl viabil",
    "Excess attrition-general",
    "Mv-train coll-anim rid",
    "DMI ophth nt st uncntrld",
    "Injury trunk nerve NOS",
    "Anaplastic lymph pelvic",
    "Cerv spondyl w myelopath",
    "Alcoh induce sleep disor",
    "Vrnt mgrn wo ntr mgr NEC",
    "Opn skull fx NEC-concuss",
    "Acq finger deformity NEC",
    "Foreign body in stomach",
    "Sleep apnea NOS",
    "Reentrant mv coll-driver",
    "Cough variant asthma",
    "Oth coll mov obj-per NEC",
    "Vac-dis combinations NOS",
    "War injury:bullet NEC",
    "Low bladder compliance",
    "Reentrant mv coll-pasngr",
    "Equatorial staphyloma",
    "Infection of kidney NOS",
    "Hemangioma retina",
    "Chr uterine subinvolutn",
    "Chr angle-clos glaucoma",
    "Acq pyloric stenosis",
    "Macular degeneration NOS",
    "Breast dis NEC-del w p/p",
    "Opn brain inj-deep coma",
    "Breech del/extrac aff NB",
    "Adv eff analgesic NOS",
    "Second iritis, noninfec",
    "Retain FB NEC",
    "Solitary cyst of breast",
    "Follow-up surgery NOS",
    "Debility NOS",
    "Ac embolism veins NEC",
    "Alcoh dep NEC/NOS-unspec",
    "RR acc w derail-employee",
    "Instrmnt fail in surgery",
    "Hepatic infarction",
    "Measles complication NOS",
    "Anal sphincter tear-old",
    "Female infertility NOS",
    "Congen limb anomaly NOS",
    "One eye-moderate/oth-NOS",
    "Poison-rabies vaccine",
    "Comp lab/deliv NEC-deliv",
    "Part resolv traum catar",
    "Unsat cerv cytlogy smear",
    "Oth dermatitis solar rad",
    "Foreign body anus/rectum",
    "Unsp ds conjuc viruses",
    "Disl metatarsal NOS-open",
    "Pneumonia e coli",
    "Cnsl victim child abuse",
    "Mycobacterial dis NEC",
    "Prophylactic isolation",
    "Posterior disloc hip-opn",
    "Erosion NOS",
    "Asympt varicose veins",
    "Intestinal abscess",
    "Hypopotassemia",
    "Chr stom ulc w hem-obstr",
    "Explosive personality",
    "Toxic effect cadmium",
    "Compl lab/deliv NEC-unsp",
    "Quadrplg c1-c4, complete",
    "Toxic shock syndrome",
    "Traffic acc NOS-driver",
    "Auditory recruitment",
    "Cns TB NEC-exam unkn",
    "Prim prg TB NEC-oth test",
    "Raynauds syndrome",
    "Opn skul fx NEC-coma NOS",
    "Chronic liver dis NOS",
    "Prune belly syndrome",
    "C1-c4 fx-op/cen cord syn",
    "Abn auditory percept NOS",
    "RR acc w derail-pedest",
    "Takayasus disease",
    "Acute respiratry failure",
    "Oth ob surg compl-postpa",
    "Chr maxillary sinusitis",
    "Renal & ureteral dis NOS",
    "Poison-vasodilator NEC",
    "Inj mlt head/neck vessel",
    "Eustachian tube dis NEC",
    "Mal neo lymph-intrapelv",
    "Obstr eustach tube NOS",
    "NB intraven hem NOS",
    "Breast engorge-delivered",
    "Genital prolapse NEC",
    "Attn rem surg dressing",
    "Mal carcinoid desc colon",
    "Face/brow present-unspec",
    "Epidem hem conjunctivit",
    "Fx gr tuberos humer-open",
    "Complete edentulism NOS",
    "Calcif tendinitis shlder",
    "Hx-analgesic allergy",
    "Rhabdomyolysis",
    "Activity NEC",
    "Mal neo lymph node NOS",
    "Endothel cornea dystrphy",
    "Cumltv trma-repetv impct",
    "Crbl art ocl NOS w infrc",
    "Venous compl NOS-postpar",
    "Quads w fetal loss-ante",
    "Spondylopathy in oth dis",
    "Edema in preg-unspec",
    "Acquired hemophilia",
    "Oil/essence pneumonitis",
    "Male genetc test dis car",
    "Papilledema w decr press",
    "Undet circ-fall residenc",
    "3rd deg burn nose",
    "Dermatophyt scalp/beard",
    "Paral polio NEC-type 1",
    "Mv brd/alight-mcycl psgr",
    "Abn pelv tis obstr-antep",
    "Diseases of nail NEC",
    "50-59% bdy brn/3 deg NOS",
    "Varicella complicat NOS",
    "Mal neo ant mediastinum",
    "Essen hyperten-delivered",
    "Talipes valgus",
    "Spotting-delivered",
    "Inj nerve pelv/leg NOS",
    "Sec DM hpros nt st uncnr",
    "Cerebral hem at birth",
    "Enceph & encephlalo NEC",
    "Acc d/t storm/flood NOS",
    "Screen neop-nervous syst",
    "Malign neopl ovary",
    "Schizophrenia NOS-unspec",
    "Unil femoral hern w gang",
    "Derang lat meniscus NOS",
    "Aggres periodontitis,loc",
    "Jt contracture-ankle",
    "Open wound of hand",
    "Lupus erythematosus",
    "Acc poison-soap products",
    "Chr iridocyclitis NOS",
    "Oth spcf hypoglycemia",
    "Plicated tongue",
    "Mental problems NEC",
    "Ocl mlt bi art w infrct",
    "Acc poison-shellfish",
    "Breast prosth malfunc",
    "Refractive amblyopia",
    "Hemangioma intracranial",
    "Acute otitis externa NEC",
    "Meningococcemia",
    "Fx c1 vertebra-closed",
    "Pois-sedative/hypnot NEC",
    "Injury arm vessels NEC",
    "Lacrimal fistula",
    "Gonorrhea-delivered",
    "Late vomit of preg-unsp",
    "Mycotic arthritis-unspec",
    "Externl cause status NEC",
    "Drug psy dis w hallucin",
    "Visceral aneurysm NEC",
    "Stat obj w sub fall NEC",
    "Brach plexus inj-birth",
    "Acc poisn-tranquilzr NOS",
    "Hpt B chrn coma wo dlta",
    "Late eff environment acc",
    "Cornea transplant status",
    "Superfic foreign bdy NEC",
    "Open wound of foot",
    "Cl skl w oth fx-mod coma",
    "Myelitis cause NEC",
    "Vaccination for Td-DT",
    "Act lymp leuk in relapse",
    "Sprain sacrospinatus",
    "Clothing fire-bldg NEC",
    "Margin zone lym head",
    "Spinal muscl atrophy NEC",
    "TB of thyroid-cult dx",
    "Oth off-road mv-st car",
    "Prim angle clos w/o dmg",
    "Sec hyprprthyrd nonrenal",
    "Monoarthritis NOS-shlder",
    "Cutan leishmanias asian",
    "Cellulitis of arm",
    "Deep vein thromb-antepar",
    "Schistosoma mansoni",
    "Blister hand",
    "Malig neo parathyroid",
    "Compl heart transplant",
    "Trypanosomiasis NOS",
    "Acq total absnc pancreas",
    "Screen-diabetes mellitus",
    "Child neglect-nutrition",
    "Second hypertension NEC",
    "Rhinosporidiosis",
    "Anomalies of uterus NEC",
    "Fx tibia NOS-open",
    "Postcatheter forgn body",
    "Brain hem NEC-brief coma",
    "Pigment epitheliopathy",
    "Nodular lymphoma abdom",
    "Burn NOS scapula",
    "Deliver-twins, both sb",
    "Intestin parasitism NOS",
    "Benign hyp ht dis w hf",
    "Angio intes w hmrhg",
    "Pectus carinatum",
    "Bacteria dis carrier NEC",
    "Crys arthrop NOS-forearm",
    "Vaginal hematoma",
    "Lichen nitidus",
    "Anphylct react milk prod",
    "Keratoconjunctivitis NOS",
    "Macular cyst or hole",
    "Coccidioidomycosis NOS",
    "Yoga",
    "Meningococcal meningitis",
    "Salivary gland atrophy",
    "Ac rheumatic myocarditis",
    "Clavicle fx at birth",
    "Ac DVT/embl up ext",
    "DMII ophth uncntrld",
    "Fx base femoral nck-open",
    "Nonpsychot brain syn NOS",
    "Contusion of upper arm",
    "TB brain abscess-cult dx",
    "Sezarys disease inguin",
    "Cong valgus foot def NEC",
    "Orchitis in oth disease",
    "Vomit of pg NOS-antepart",
    "Lt-date w/mal 1500-1749g",
    "Cl skl fx NEC-proln coma",
    "Venous tributary occlus",
    "Mv board/alight-pers NEC",
    "Helminth arthrit-forearm",
    "Poisoning-tetanus vaccin",
    "Fail induct NOS-antepart",
    "Oth spcf hypoglycemia",
    "Thromboangiit obliterans",
    "Cellulitis, toe NOS",
    "Drowning/nonfatal submer",
    "Long QT syndrome",
    "Unc behav neo placenta",
    "Cardiorespirat probl NEC",
    "Mucositis d/t drugs NEC",
    "Gross hematuria",
    "Pneumonia due to SARS",
    "Pelv deform NOS-antepart",
    "Chr membranoprolif nephr",
    "Late eff nerve inj NEC",
    "Acc pois-solid/liq NEC",
    "Exudat cyst pars plana",
    "Twin-mate lb-hosp w/o cs",
    "Hx of emotional abuse",
    "Screen-diabetes mellitus",
    "Recur depr psych-severe",
    "TB of ureter-micro dx",
    "Alcohol mental disor NOS",
    "Other pulmonary insuff",
    "Hx-malig skin melanoma",
    "Dermatophytosis of groin",
    "Pulmon embol NEC-deliver",
    "Hodg nodul sclero mult",
    "Toxic effect antimony",
    "Request expert evidence",
    "Monoarthritis NOS-unspec",
    "Subarach hem w opn wound",
    "Varic vein leg-postpart",
    "Abn react-procedure NOS",
    "Strep sore throat",
    "2nd deg burn abdomn wall",
    "Trigeminal neuralgia",
    "Multiple sclerosis",
    "Ankylosis-mult joints",
    "Injury ovarian artery",
    "Unc behav neo testis",
    "Cl skull vlt fx-brf coma",
    "C1-c4 spin cord inj NOS",
    "Sprain of foot NEC",
    "Leg abor w pelv inf-unsp",
    "Hypervitaminosis d",
    "Ophthalmia nodosa",
    "Oligohydramnios-deliver",
    "Toxic gastroenteritis",
    "GI injury NEC-open",
    "BMI 33.0-33.9,adult",
    "Straining on urination",
    "Battering by child",
    "Esotropia NOS",
    "Isolated explosive dis",
    "Hyperem w metab dis-unsp",
    "Klinefelters syndrome",
    "Renal failure NOS",
    "Iatrogen CV infarc/hmrhg",
    "Inj int mammary art/vein",
    "Ca in situ fem gen NEC",
    "Lacrimal syst dis NEC",
    "Toxoplasma pneumonitis",
    "Poison-fibrinolysis agnt",
    "Inflam/tox neuropthy NOS",
    "Nephritis NOS",
    "Family dsrpt-estrangmemt",
    "Unstable lie-delivered",
    "Siderosis",
    "Vestibular neuronitis",
    "Abn amnion NEC aff NB",
    "Thoracoabd aortc ectasia",
    "Granuloma of conjunctiva",
    "Great vein anomaly NOS",
    "Affectiv personality NOS",
    "Tox eff lead compnd NOS",
    "Laundry",
    "Lordosis NOS",
    "Craniorachischisis",
    "Jt derangement NEC-mult",
    "Fetal malnutr 1750-1999g",
    "Dev disloc jt-site NEC",
    "Cong anom of aorta NOS",
    "Periostitis-unspec",
    "Bursal cyst NEC",
    "Acute otitis externa NEC",
    "Opn skl/oth fx-deep coma",
    "Gouty tophi of ear",
    "Brach plexus inj-birth",
    "Disorders of eyelid NEC",
    "Aftercare path fx hip",
    "TB of joint NEC-no exam",
    "Benign parxysmal vertigo",
    "Inf mcr rst qn flr nt ml",
    "Conjunctival concretions",
    "Spleen disease NOS",
    "Unc behav neo breast",
    "Prim TB pleur-exam unkn",
    "Influenza with pneumonia",
    "Postop shock, other",
    "Subendo infarct, initial",
    "Syphil acoustic neuritis",
    "Neonatal neutropenia",
    "Pyoderma NEC",
    "Acc poisn-alcohol bevrag",
    "Impotence, organic orign",
    "Dis calcium metablsm NEC",
    "Argentous cornea deposit",
    "Deep 3rd deg burn foot",
    "Cl skull fx NEC w/o coma",
    "Shigella infection NEC",
    "Fx base femoral nck-open",
    "Mening in oth fungal dis",
    "Cardiogenic shock",
    "Abn chromosomal analysis",
    "Lifting machine accident",
    "Effect reduced temp NEC",
    "Abdmnal mass rt upr quad",
    "Insect bite shld/arm-inf",
    "Inj internl jugular vein",
    "Lymphocytopenia",
    "Unc behav neo testis",
    "Polio osteopathy-hand",
    "Chr pulmonary embolism",
    "Heat edema",
    "Battering by sibling",
    "Obsrv NB suspc resp cond",
    "Screen-iron defic anemia",
    "Persistent fetal circ",
    "Idiopth lym interst pneu",
    "Loose body-ankle",
    "Hx-prostatic malignancy",
    "Cord prolapse-antepartum",
    "Teething syndrome",
    "Ankylosis-lower/leg",
    "Ovarian hyperfunc NEC",
    "Ocl vrtb art w infrct",
    "Pressure ulcer, heel",
    "Left bb block NEC",
    "Leg ab w metab dis-comp",
    "Antenatal screening NEC",
    "Ocl art NOS w infrct",
    "No medical serv in home",
    "Fracture six ribs-closed",
    "Open wound of ear NOS",
    "Nontox multinodul goiter",
    "Juv osteochondros spine",
    "Mv coll w obj-pedest",
    "Mech loosening pros jt",
    "Twin gest-dich/diamniotc",
    "Placent polyp-del w p/p",
    "Histoplasmosis NOS",
    "Comp-oth vasc dev/graft",
    "Joint symptom NEC-hand",
]
