SAVEPOINT sav2;

SELECT COUNT(*) as count_before FROM DOCTOR;

DELETE FROM DOCTOR
WHERE DOCTORID IN (
  SELECT DISTINCT DOCTORID
  FROM MEDICATION 
  INNER JOIN MEDICATION_TREATMENT USING(MEDICATIONID)
  INNER JOIN TREATMENT USING(TREATMENTID)
  INNER JOIN DOCTOR USING(DOCTORID)
  INNER JOIN PATIENT USING(PATIENTID)
  WHERE EXPIRATIONDATE < TREATMENTDATE
);

SELECT COUNT(*) as count_after FROM DOCTOR;

ROLLBACK TO sav2;
