SAVEPOINT sav1;

SELECT COUNT(*) as count_before FROM DEPARTMENT;

DELETE FROM DEPARTMENT D
WHERE NOT EXISTS (
      SELECT DEPARTMENTID
      FROM DOCTOR
      WHERE D.DEPARTMENTID = DOCTOR.DEPARTMENTID
) 
AND DEPARTMENTID NOT IN (
      SELECT DISTINCT DEPARTMENTID
      FROM ROOM
);

SELECT COUNT(*) as count_after FROM DEPARTMENT;

ROLLBACK TO sav1;
