SELECT MEDICATIONID, NAME, QUANTITYINSTOCK FROM MEDICATION
WHERE QUANTITYINSTOCK < 30
AND MEDICATIONID IN (
    SELECT MEDICATIONID FROM TREATMENT
    INNER JOIN MEDICATION_TREATMENT USING(TREATMENTID)
    INNER JOIN MEDICATION USING(MEDICATIONID)
    GROUP BY MEDICATIONID
    HAVING COUNT(TREATMENTID) >= ALL(
          SELECT COUNT(TREATMENTID) FROM TREATMENT
          INNER JOIN MEDICATION_TREATMENT USING(TREATMENTID)
          INNER JOIN MEDICATION USING(MEDICATIONID)
          GROUP BY MEDICATIONID 
    )
)
ORDER BY QUANTITYINSTOCK
