SELECT DOCTORID, NAME, SPECIALTY, PHONE, COUNT(TREATMENTID) AS treat_count
FROM (
     SELECT * FROM DOCTOR
     INNER JOIN TREATMENT USING(DOCTORID)
     WHERE TREATMENTDATE >= TO_DATE('2004', 'YYYY')
)
GROUP BY DOCTORID, NAME, SPECIALTY, PHONE
HAVING COUNT(TREATMENTID) >= 5
ORDER BY treat_count DESC 
