SELECT DEPARTMENT.NAME AS DEPARTMENT_NAME, 
       PATIENT.NAME AS PATIENT_NAME, ROOM.TYPE
FROM PATIENT
LEFT JOIN ROOM USING (ROOMID)
LEFT JOIN DEPARTMENT USING (DEPARTMENTID)
WHERE DEPARTMENTID IN (
  SELECT DEPARTMENTID
  FROM (
    SELECT DEPARTMENTID, COUNT(PATIENTID) AS PATIENT_COUNT
    FROM PATIENT
    LEFT JOIN ROOM USING (ROOMID)
    LEFT JOIN DEPARTMENT USING (DEPARTMENTID)
    GROUP BY DEPARTMENTID
  )
  WHERE PATIENT_COUNT > 5
);
