SELECT MEDICATION.NAME AS M_NAME, DOCTOR.NAME AS D_NAME, DOCTOR.PHONE AS D_PHONE, 
       PATIENT.NAME AS P_NAME, PATIENT.PHONE AS P_PHONE, EXPIRATIONDATE, TREATMENTDATE
FROM MEDICATION 
INNER JOIN MEDICATION_TREATMENT USING(MEDICATIONID)
INNER JOIN TREATMENT USING(TREATMENTID)
INNER JOIN DOCTOR USING(DOCTORID)
INNER JOIN PATIENT USING(PATIENTID)
--WHERE EXPIRATIONDATE < TREATMENTDATE
WHERE EXTRACT(YEAR FROM TREATMENTDATE) > EXTRACT(YEAR FROM EXPIRATIONDATE)
OR EXTRACT(MONTH FROM TREATMENTDATE) > EXTRACT(MONTH FROM EXPIRATIONDATE)
OR EXTRACT(DAY FROM TREATMENTDATE) - EXTRACT(DAY FROM EXPIRATIONDATE) > 10
